apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  labels:
    group: microservices
spec:
  selector:
    app: api-gateway
  ports:
    - port: 9090
      targetPort: 9090
  type: LoadBalancer