apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service-deployment
  labels:
    group: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-service
  template:
    metadata:
      name: eureka-service
      labels:
        app: eureka-service
    spec:
      containers:
        - name: eureka-service
          image: denyslitvinov/eureka-service
          ports:
            - containerPort: 8761