apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-service-deployment
  labels:
    group: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-service
  template:
    metadata:
      name: student-service
      labels:
        app: student-service
    spec:
      containers:
        - name: student-service
          image: denyslitvinov/student-service
          ports:
            - containerPort: 8080
          env:
            - name: EUREKA_SERVICE
              value: http://eureka-service-service.default:8761/eureka/
            - name: DB_URL
              value: mysql-service.default